# Generated by Django 2.0.6 on 2018-06-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('power', models.IntegerField()),
                ('light', models.BooleanField()),
                ('imageUrl', models.CharField(max_length=128)),
                ('affiliations', models.ManyToManyField(to='starwars.Affiliation')),
            ],
        ),
    ]
