# Generated by Django 2.0.6 on 2018-06-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'Heroes'},
        ),
    ]
